### ISSUE TITLE
Feedback regarding the At (U+0040) character

### ISSUE THREAD

**Issue by galdor** [berkeleygraphics/berkeley-mono#9]
It feels to me that the At character is a bit too "geometrical", in a way that really stands out among other characters.

If you look at other characters containing closed loops, such as 'a', 'g', '©' and '®', the external part of '@' is really boxy:

![image](https://user-images.githubusercontent.com/37804/156939684-d9c84205-91b4-474b-81b3-c0e6ab3c51d3.png)

What do you think about it?

**Comment by neilpanchal** [comment]
Hi @galdor Thanks for the feedback. Your observation is totally correct and while it is slightly geometric, the intention was to make it stand out as a symbol in text. © has different application (foo@bar.com vs. © bar.com) where there is a lot more space.  I'm closing this issue since it would be a major change and I respect your obversation :)
